---
title: "About"
---

## Background and Why I'm Running

We moved to Fair Haven in early 2021 during the Pandemic in search of a family-oriented community down the shore with excellent schools and in commuting distance to NYC. Fair Haven certainly fit the bill. Fast forward a few years and we are fully integrated into the FH community, with a first grader and pre-K-er both at Sickles.

Professionally, I spent the first half of my career working in education and related industries. During college, I worked as a research assistant at the Cornell Higher Education Research Institute ([CHERI](https://ecommons.cornell.edu/collections/ea0fd99b-5bec-4094-b002-bd14ca8e2368)) studying determinants of faculty productivity. Shortly after, I spent a year at a policy evaluation firm measuring the impacts of federally funded early childhood centers. I then entered graduate school at Teachers College, Columbia University to pursue a degree in economics and education while working at the Community College Research Center ([CCRC](https://ccrc.tc.columbia.edu/)). A few years in, I decided that I needed some more grounded experience, and took two years off to be a mathematics and statistics teacher at a growing American school in Cancún, Mexico. I eventually returned to New York City and Columbia to finish graduate school before venturing out into the world of EdTech, where I worked as a researcher and data scientist at several startups. I've since left the education world professionally, but am still focused on research, data, and decision-making as a quantitative user experience researcher at a global technology company.

As I have been following the current Fair Haven district budget situation, and thinking about the long-term investments that me and my family are making in the community, it seemed like a natural next step to get more involved and to contribute a data-drive, outcome-oriented voice to these important issues facing our community and schools. It's almost as if I have been preparing my whole life for this opportunity, and I am excited to get started.

For more info, check out my [resume](files/crosta_resume_2025.pdf) or [Google Scholar](https://scholar.google.com/citations?user=M1or3F8AAAAJ&hl=en) profile.
