---
format: html
date: last-modified
---

# **Running for School Board: The Petition and Campaign Finance**

## **Intro**

Running for school board required a number of steps that I wanted to document, both for myself and for others who may be considered running. This article contains details on two parts of the process I had to manage: the petition and campaign finance. Since I ran what turned out to be an uncontested campaign (with the exception of write-ins), I did not actually engage in the creation and dissemination of any campaign literature. If I had, I would have included that process here as well.

## **The Petition**

In order to get on the ballot, you must get 25 signatures from individuals who are eligible to vote in the district. From what I understand, these must be registered voters, as the County cross-references the signatures with voter registration rolls.

I downloaded and printed the petition from the NJ School Board Association (NJSBA) Candidacy [website](https://www.njsba.org/membership/membership-school-board-members/school-board-candidacy/). The file was titled "Sample Nominating Petition Individual Nov. 2025," and it was a **`.docx`** file (a `pdf` would have been more appropriate). I found it super strange that this organization seemed to be the only one that housed these petitions. In fact, I initially e-mailed the Monmouth County Clerk to ask about this - assuming that they would have something - and they sent me to the NJSBA.

I spent the summer carrying around the petition form to any event where there was a gathering of people. Eventually, I managed to get 25 signatures. However, I received some good advice from a previous candidate who suggested acquiring several more signatures just in case. Despite best intentions, some signatories may not be valid for a number of reasons.

Next, I proceeded to have parts C and D of the petition notarized at Borough Hall. I originally thought I could submit the forms there as well, but this was incorrect. The entire nominating petition must be delivered to the County Clerk in Freehold. It is possible to mail it in, but I drove out there and dropped it off directly with the Clerk. I expected to receive some kind of receipt, but when I asked, the receptionist gave me a confused look.d to trust the process. It seemed to all work out, but a receipt of sorts would have provided some peace of mind.

## **Campaign Finance**

One of the more complicated aspects of running for office involves campaign finance considerations. As soon as you declare candidacy, you are considered a candidate subject to the laws regarding campaign finance in the State. The system that governs national elections with millions of dollars is the same as the one that governs local elections with potentially hundreds of dollars at stake. There are of course some material differences in what forms that need to be filed, but there was still quite a bit to do.

Note: I am not a lawyer and nothing here should be construed as legal advice; this is solely a record of my experience.

Core to campaign finance is having a separate bank account for the campaign. Any money that is spent to support a candidate being elected must come out of this bank account. And all money entering the bank account must be disclosed. This all happens by filing a bunch of forms with [NJ ELEC](https://www.elec.nj.gov/https://www.elec.nj.gov/).

Now, in order to do anything on NJ ELEC, you need a bank account. And in order to get a bank account for a campaign, you need an EIN (Employer Identification Number). This comes from the Federal IRS. I went through an IRS [self-service portal](https://www.irs.gov/businesses/small-businesses-self-employed/get-an-employer-identification-number) to register my campaign as a legal entity and get an EIN. In the online flow, I chose “Political Organization” as the type of structure, indicated it was for Banking Purposes, established myself as the responsible party, and claimed that the entity’s legal name was “Peter Crosta for BOE.”

Then I had to file an [8871](https://forms.irs.gov/app/pof/form8871/initial). This is where things get complicated. In order to file the 8871, you must *also* file an [8453-X](https://www.irs.gov/pub/irs-access/f8453x_accessible.pdf). But the 8453-X asks for the date and time that the 8871 was filed - a classic chicken-and-egg problem.

There is a somewhat-hidden note on one of the IRS pages that explains the process: “First time users of the Political Organization Filing program can file their initial Form 8871 prior to receiving a username and password. Upon completion of the initial Form 8871 users will be instructed to print, sign and mail a Form 8453-X, Declaration of Electronic Filing. Upon receipt of Form 8453-X, the IRS will mail the username and password to the organization.”

So, the correct (but confusing) procedure is: you must first file an [initial 8871](https://forms.irs.gov/app/pof/form8871/initial), and after receiving a user name and password, you [go back in](https://forms.irs.gov/app/pof/login-page) to amend the 8871.

Next, you can register yourself in ELEC by filing a form D-1. This begins with the APPLICATION FOR REGISTRATION NUMBER AND PERSONAL IDENTIFICATION NUMBER (PIN) so that you can e-SIGN Form D-1. Great, but Form D-1 requires you to declare a bank account.

For banking, I did not expect to spend large sums of money and wanted the simplest free checking offering imaginable. I also did not want an interest-bearing account (as that creates additional tax and filing burdens). Luckily, a local bank called Provident Bank offers a no-fee small business checking. I went to my local branch and asked to open up an account.

However, in order to open an account, they wanted to see my EIN (got that), 2 forms of ID (no prob), and the form D-1. But wait - the D-1 requires you to declare a bank account AND the bank account requires the D-1.

This was a stressful moment. After some digging, I learned that you can file a D-1 *without* entering bank account information. You can then use this to open the bank account. And *then* you can AMEND the D-1 after the bank account is created. What a system!

Ultimately, it all worked out. And within a few days, I received a debit card in the mail that I could use for campaign-related purchases. Before I knew that I was unlikely to spend any money on campaigning, I wrote a personal check and deposited it in the campaign account in case I needed it. I then filed form C-1 with ELEC to stay in reporting compliance.

## **Conclusion**

I wrote this article both as a reminder to myself and as a guide to future school board candidates. Though it generally “all worked out eventually,” I would have appreciated knowing a bit more about the process before embarking on it myself.
